// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/trend-me/ai-prompt-builder/internal/config/connections"
	"github.com/trend-me/ai-prompt-builder/internal/config/properties"
	"github.com/trend-me/ai-prompt-builder/internal/delivery/controllers"
	"github.com/trend-me/ai-prompt-builder/internal/domain/interfaces"
	"github.com/trend-me/ai-prompt-builder/internal/domain/usecases"
	"github.com/trend-me/ai-prompt-builder/internal/integration/api"
	"github.com/trend-me/ai-prompt-builder/internal/integration/queue"
	"github.com/trend-me/golang-rabbitmq-lib/rabbitmq"
)

// Injectors from wire.go:

func InitializeConsumer() (func(), error) {
	urlApiPromptRoadMap := NewUrlApiPromptRoadMap()
	apiPromptRoadMap := api.NewPromptRoadMap(urlApiPromptRoadMap)
	urlApiValidation := NewUrlApiValidation()
	apiValidation := api.NewValidation(urlApiValidation)
	connection, err := connections.ConnectQueue()
	if err != nil {
		return nil, err
	}
	connectionAiPromptBuilder := NewQueueNameAiPromptBuilder(connection)
	queueAiRequester := queue.NewAiRequester(connectionAiPromptBuilder)
	useCase := usecases.NewUseCase(apiPromptRoadMap, apiValidation, queueAiRequester)
	controller := controllers.NewController(useCase)
	v := NewConsumer(controller, connectionAiPromptBuilder)
	return v, nil
}

// wire.go:

func NewQueueNameAiPromptBuilder(connection *rabbitmq.Connection) queue.ConnectionAiPromptBuilder {
	return rabbitmq.NewQueue(
		connection, properties.QueueNameAiPromptBuilder, rabbitmq.ContentTypeJson, properties.CreateQueueIfNX(), true,
		true,
	)
}

func NewConsumer(controller interfaces.Controller, connectionAiPromptBuilder queue.ConnectionAiPromptBuilder) func() {
	return func() {
		connectionAiPromptBuilder.Consume(context.Background(), controller.Handle)
	}
}

func NewUrlApiValidation() api.UrlApiValidation {
	return properties.UrlApiValidation
}

func NewUrlApiPromptRoadMap() api.UrlApiPromptRoadMap {
	return properties.UrlApiPromptRoadMap
}
